business:
    type: rest
    resource: Aescarcha\BusinessBundle\Controller\BusinessController

employee:
    type: rest    
    parent: business
    resource: Aescarcha\EmployeeBundle\Controller\EmployeeController